//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelYonetimSistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EksikMesaiKayitlari
    {
        public int EksikMesaiID { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public System.DateTime EksikMesaiTarihi { get; set; }
        public decimal EksikSure { get; set; }
        public decimal KesilisTutari { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Personel Personel { get; set; }
    }
}
