//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelYonetimSistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzinKayitlari
    {
        public int IzinID { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<int> IzinTurID { get; set; }
        public System.DateTime BaslangicTarihi { get; set; }
        public System.DateTime BitisTarihi { get; set; }
        public int IzinGunSayisi { get; set; }
        public string OnayDurumu { get; set; }
        public string Aciklama { get; set; }
    
        public virtual IzinTurleri IzinTurleri { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
