//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelYonetimSistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menuler
    {
        public int menu_id { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public int yemek_id { get; set; }
        public string ogun_turu { get; set; }
    
        public virtual Yemekler Yemekler { get; set; }
    }
}
