//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelYonetimSistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesaiKayitlari
    {
        public int MesaiID { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<int> MesaiTurID { get; set; }
        public System.DateTime MesaiTarihi { get; set; }
        public System.TimeSpan BaslangicSaati { get; set; }
        public System.TimeSpan BitisSaati { get; set; }
        public decimal MesaiSuresi { get; set; }
        public decimal MesaiUcreti { get; set; }
        public Nullable<bool> Onaylandi { get; set; }
        public string Aciklama { get; set; }
    
        public virtual MesaiTurleri MesaiTurleri { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
