//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelYonetimSistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Odalar()
        {
            this.Rezervasyons = new HashSet<Rezervasyons>();
        }
    
        public int OdaID { get; set; }
        public int Kat { get; set; }
        public string OdaNumarasi { get; set; }
        public string OdaTuru { get; set; }
        public Nullable<decimal> GecelikFiyat { get; set; }
        public Nullable<int> KisiSayisi { get; set; }
        public string Durum { get; set; }
        public string Aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervasyons> Rezervasyons { get; set; }
    }
}
