//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelYonetimSistemi.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OtelYonetimiDbEntities : DbContext
    {
        public OtelYonetimiDbEntities()
            : base("name=OtelYonetimiDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departmanlar> Departmanlar { get; set; }
        public virtual DbSet<EksikMesaiKayitlari> EksikMesaiKayitlari { get; set; }
        public virtual DbSet<IzinKayitlari> IzinKayitlari { get; set; }
        public virtual DbSet<IzinTurleri> IzinTurleri { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<Maaslar> Maaslar { get; set; }
        public virtual DbSet<Menuler> Menuler { get; set; }
        public virtual DbSet<MesaiKayitlari> MesaiKayitlari { get; set; }
        public virtual DbSet<MesaiTurleri> MesaiTurleri { get; set; }
        public virtual DbSet<Misafirs> Misafirs { get; set; }
        public virtual DbSet<Odalar> Odalar { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<PersonelVardiyalari> PersonelVardiyalari { get; set; }
        public virtual DbSet<Pozisyonlar> Pozisyonlar { get; set; }
        public virtual DbSet<Rezervasyons> Rezervasyons { get; set; }
        public virtual DbSet<SigortaBilgileri> SigortaBilgileri { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
        public virtual DbSet<VardiyaTurleri> VardiyaTurleri { get; set; }
        public virtual DbSet<Yemek_Hazirlama> Yemek_Hazirlama { get; set; }
        public virtual DbSet<Yemek_Malzemeleri> Yemek_Malzemeleri { get; set; }
        public virtual DbSet<Yemekler> Yemekler { get; set; }
    }
}
