//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelYonetimSistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelVardiyalari
    {
        public int VardiyaID { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<int> VardiyaTurID { get; set; }
        public System.DateTime VardiyaTarihi { get; set; }
        public string DurumNotu { get; set; }
    
        public virtual Personel Personel { get; set; }
        public virtual VardiyaTurleri VardiyaTurleri { get; set; }
    }
}
