//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelYonetimSistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel()
        {
            this.EksikMesaiKayitlari = new HashSet<EksikMesaiKayitlari>();
            this.IzinKayitlari = new HashSet<IzinKayitlari>();
            this.Maaslar = new HashSet<Maaslar>();
            this.MesaiKayitlari = new HashSet<MesaiKayitlari>();
            this.PersonelVardiyalari = new HashSet<PersonelVardiyalari>();
            this.SigortaBilgileri = new HashSet<SigortaBilgileri>();
        }
    
        public int PersonelID { get; set; }
        public string TCKimlikNo { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public System.DateTime DogumTarihi { get; set; }
        public string Cinsiyet { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public System.DateTime IseBaslamaTarihi { get; set; }
        public Nullable<System.DateTime> IstenAyrilmaTarihi { get; set; }
        public Nullable<int> PozisyonID { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EksikMesaiKayitlari> EksikMesaiKayitlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzinKayitlari> IzinKayitlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maaslar> Maaslar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MesaiKayitlari> MesaiKayitlari { get; set; }
        public virtual Pozisyonlar Pozisyonlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelVardiyalari> PersonelVardiyalari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SigortaBilgileri> SigortaBilgileri { get; set; }
    }
}
