//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelYonetimSistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyons
    {
        public int Id { get; set; }
        public int MisafirId { get; set; }
        public int OdaId { get; set; }
        public System.DateTime BaslangicTarihi { get; set; }
        public System.DateTime BitisTarihi { get; set; }
        public int KisiSayisi { get; set; }
        public string Durum { get; set; }
        public decimal Fiyat { get; set; }
        public string OdaNumarasi { get; set; }
    
        public virtual Misafirs Misafirs { get; set; }
        public virtual Odalar Odalar { get; set; }
    }
}
