//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelYonetimSistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SigortaBilgileri
    {
        public int SigortaID { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public string SigortaNo { get; set; }
        public System.DateTime BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public string SigortaTuru { get; set; }
        public decimal AylikPrim { get; set; }
    
        public virtual Personel Personel { get; set; }
    }
}
