//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelYonetimSistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.Yemek_Malzemeleri = new HashSet<Yemek_Malzemeleri>();
        }
    
        public int urun_id { get; set; }
        public string urun_adi { get; set; }
        public int kategori_id { get; set; }
        public decimal stok_miktari { get; set; }
        public string birim { get; set; }
        public Nullable<System.DateTime> son_kullanma_tarihi { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yemek_Malzemeleri> Yemek_Malzemeleri { get; set; }
    }
}
