//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelYonetimSistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VardiyaTurleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VardiyaTurleri()
        {
            this.PersonelVardiyalari = new HashSet<PersonelVardiyalari>();
        }
    
        public int VardiyaTurID { get; set; }
        public string VardiyaAdi { get; set; }
        public System.TimeSpan BaslangicSaati { get; set; }
        public System.TimeSpan BitisSaati { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelVardiyalari> PersonelVardiyalari { get; set; }
    }
}
