//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelYonetimSistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yemek_Malzemeleri
    {
        public int yemek_id { get; set; }
        public int urun_id { get; set; }
        public decimal miktar { get; set; }
        public string birim { get; set; }
    
        public virtual Urunler Urunler { get; set; }
        public virtual Yemekler Yemekler { get; set; }
    }
}
